// Code generated by go-swagger; DO NOT EDIT.

package payer_authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPayerAuthSetupParams creates a new PayerAuthSetupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPayerAuthSetupParams() *PayerAuthSetupParams {
	return &PayerAuthSetupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPayerAuthSetupParamsWithTimeout creates a new PayerAuthSetupParams object
// with the ability to set a timeout on a request.
func NewPayerAuthSetupParamsWithTimeout(timeout time.Duration) *PayerAuthSetupParams {
	return &PayerAuthSetupParams{
		timeout: timeout,
	}
}

// NewPayerAuthSetupParamsWithContext creates a new PayerAuthSetupParams object
// with the ability to set a context for a request.
func NewPayerAuthSetupParamsWithContext(ctx context.Context) *PayerAuthSetupParams {
	return &PayerAuthSetupParams{
		Context: ctx,
	}
}

// NewPayerAuthSetupParamsWithHTTPClient creates a new PayerAuthSetupParams object
// with the ability to set a custom HTTPClient for a request.
func NewPayerAuthSetupParamsWithHTTPClient(client *http.Client) *PayerAuthSetupParams {
	return &PayerAuthSetupParams{
		HTTPClient: client,
	}
}

/* PayerAuthSetupParams contains all the parameters to send to the API endpoint
   for the payer auth setup operation.

   Typically these are written to a http.Request.
*/
type PayerAuthSetupParams struct {

	// PayerAuthSetupRequest.
	PayerAuthSetupRequest PayerAuthSetupBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the payer auth setup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PayerAuthSetupParams) WithDefaults() *PayerAuthSetupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the payer auth setup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PayerAuthSetupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the payer auth setup params
func (o *PayerAuthSetupParams) WithTimeout(timeout time.Duration) *PayerAuthSetupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the payer auth setup params
func (o *PayerAuthSetupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the payer auth setup params
func (o *PayerAuthSetupParams) WithContext(ctx context.Context) *PayerAuthSetupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the payer auth setup params
func (o *PayerAuthSetupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the payer auth setup params
func (o *PayerAuthSetupParams) WithHTTPClient(client *http.Client) *PayerAuthSetupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the payer auth setup params
func (o *PayerAuthSetupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayerAuthSetupRequest adds the payerAuthSetupRequest to the payer auth setup params
func (o *PayerAuthSetupParams) WithPayerAuthSetupRequest(payerAuthSetupRequest PayerAuthSetupBody) *PayerAuthSetupParams {
	o.SetPayerAuthSetupRequest(payerAuthSetupRequest)
	return o
}

// SetPayerAuthSetupRequest adds the payerAuthSetupRequest to the payer auth setup params
func (o *PayerAuthSetupParams) SetPayerAuthSetupRequest(payerAuthSetupRequest PayerAuthSetupBody) {
	o.PayerAuthSetupRequest = payerAuthSetupRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PayerAuthSetupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.PayerAuthSetupRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
