// Code generated by go-swagger; DO NOT EDIT.

package asymmetric_key_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteBulkP12KeysParams creates a new DeleteBulkP12KeysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteBulkP12KeysParams() *DeleteBulkP12KeysParams {
	return &DeleteBulkP12KeysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBulkP12KeysParamsWithTimeout creates a new DeleteBulkP12KeysParams object
// with the ability to set a timeout on a request.
func NewDeleteBulkP12KeysParamsWithTimeout(timeout time.Duration) *DeleteBulkP12KeysParams {
	return &DeleteBulkP12KeysParams{
		timeout: timeout,
	}
}

// NewDeleteBulkP12KeysParamsWithContext creates a new DeleteBulkP12KeysParams object
// with the ability to set a context for a request.
func NewDeleteBulkP12KeysParamsWithContext(ctx context.Context) *DeleteBulkP12KeysParams {
	return &DeleteBulkP12KeysParams{
		Context: ctx,
	}
}

// NewDeleteBulkP12KeysParamsWithHTTPClient creates a new DeleteBulkP12KeysParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteBulkP12KeysParamsWithHTTPClient(client *http.Client) *DeleteBulkP12KeysParams {
	return &DeleteBulkP12KeysParams{
		HTTPClient: client,
	}
}

/* DeleteBulkP12KeysParams contains all the parameters to send to the API endpoint
   for the delete bulk p12 keys operation.

   Typically these are written to a http.Request.
*/
type DeleteBulkP12KeysParams struct {

	// DeleteBulkP12KeysRequest.
	DeleteBulkP12KeysRequest DeleteBulkP12KeysBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete bulk p12 keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBulkP12KeysParams) WithDefaults() *DeleteBulkP12KeysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete bulk p12 keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBulkP12KeysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete bulk p12 keys params
func (o *DeleteBulkP12KeysParams) WithTimeout(timeout time.Duration) *DeleteBulkP12KeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete bulk p12 keys params
func (o *DeleteBulkP12KeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete bulk p12 keys params
func (o *DeleteBulkP12KeysParams) WithContext(ctx context.Context) *DeleteBulkP12KeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete bulk p12 keys params
func (o *DeleteBulkP12KeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete bulk p12 keys params
func (o *DeleteBulkP12KeysParams) WithHTTPClient(client *http.Client) *DeleteBulkP12KeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete bulk p12 keys params
func (o *DeleteBulkP12KeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeleteBulkP12KeysRequest adds the deleteBulkP12KeysRequest to the delete bulk p12 keys params
func (o *DeleteBulkP12KeysParams) WithDeleteBulkP12KeysRequest(deleteBulkP12KeysRequest DeleteBulkP12KeysBody) *DeleteBulkP12KeysParams {
	o.SetDeleteBulkP12KeysRequest(deleteBulkP12KeysRequest)
	return o
}

// SetDeleteBulkP12KeysRequest adds the deleteBulkP12KeysRequest to the delete bulk p12 keys params
func (o *DeleteBulkP12KeysParams) SetDeleteBulkP12KeysRequest(deleteBulkP12KeysRequest DeleteBulkP12KeysBody) {
	o.DeleteBulkP12KeysRequest = deleteBulkP12KeysRequest
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBulkP12KeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.DeleteBulkP12KeysRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
