// Code generated by go-swagger; DO NOT EDIT.

package interchange_clearing_level_details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInterchangeClearingLevelDetailsParams creates a new GetInterchangeClearingLevelDetailsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInterchangeClearingLevelDetailsParams() *GetInterchangeClearingLevelDetailsParams {
	return &GetInterchangeClearingLevelDetailsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInterchangeClearingLevelDetailsParamsWithTimeout creates a new GetInterchangeClearingLevelDetailsParams object
// with the ability to set a timeout on a request.
func NewGetInterchangeClearingLevelDetailsParamsWithTimeout(timeout time.Duration) *GetInterchangeClearingLevelDetailsParams {
	return &GetInterchangeClearingLevelDetailsParams{
		timeout: timeout,
	}
}

// NewGetInterchangeClearingLevelDetailsParamsWithContext creates a new GetInterchangeClearingLevelDetailsParams object
// with the ability to set a context for a request.
func NewGetInterchangeClearingLevelDetailsParamsWithContext(ctx context.Context) *GetInterchangeClearingLevelDetailsParams {
	return &GetInterchangeClearingLevelDetailsParams{
		Context: ctx,
	}
}

// NewGetInterchangeClearingLevelDetailsParamsWithHTTPClient creates a new GetInterchangeClearingLevelDetailsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInterchangeClearingLevelDetailsParamsWithHTTPClient(client *http.Client) *GetInterchangeClearingLevelDetailsParams {
	return &GetInterchangeClearingLevelDetailsParams{
		HTTPClient: client,
	}
}

/* GetInterchangeClearingLevelDetailsParams contains all the parameters to send to the API endpoint
   for the get interchange clearing level details operation.

   Typically these are written to a http.Request.
*/
type GetInterchangeClearingLevelDetailsParams struct {

	/* EndTime.

	     Valid report End Time in **ISO 8601 format**
	Please refer the following link to know more about ISO 8601 format.[Rfc Date Format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14)

	**Example date format:**
	  - yyyy-MM-dd'T'HH:mm:ss.SSSZ (e.g. 2018-01-01T00:00:00.000Z)


	     Format: date-time
	*/
	EndTime strfmt.DateTime

	/* OrganizationID.

	   Valid Organization Id
	*/
	OrganizationID *string

	/* StartTime.

	     Valid report Start Time in **ISO 8601 format**
	Please refer the following link to know more about ISO 8601 format.[Rfc Date Format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14)

	**Example date format:**
	  - yyyy-MM-dd'T'HH:mm:ss.SSSZ (e.g. 2018-01-01T00:00:00.000Z)


	     Format: date-time
	*/
	StartTime strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get interchange clearing level details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInterchangeClearingLevelDetailsParams) WithDefaults() *GetInterchangeClearingLevelDetailsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get interchange clearing level details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInterchangeClearingLevelDetailsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) WithTimeout(timeout time.Duration) *GetInterchangeClearingLevelDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) WithContext(ctx context.Context) *GetInterchangeClearingLevelDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) WithHTTPClient(client *http.Client) *GetInterchangeClearingLevelDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEndTime adds the endTime to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) WithEndTime(endTime strfmt.DateTime) *GetInterchangeClearingLevelDetailsParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) SetEndTime(endTime strfmt.DateTime) {
	o.EndTime = endTime
}

// WithOrganizationID adds the organizationID to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) WithOrganizationID(organizationID *string) *GetInterchangeClearingLevelDetailsParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) SetOrganizationID(organizationID *string) {
	o.OrganizationID = organizationID
}

// WithStartTime adds the startTime to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) WithStartTime(startTime strfmt.DateTime) *GetInterchangeClearingLevelDetailsParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the get interchange clearing level details params
func (o *GetInterchangeClearingLevelDetailsParams) SetStartTime(startTime strfmt.DateTime) {
	o.StartTime = startTime
}

// WriteToRequest writes these params to a swagger request
func (o *GetInterchangeClearingLevelDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param endTime
	qrEndTime := o.EndTime
	qEndTime := qrEndTime.String()
	if qEndTime != "" {

		if err := r.SetQueryParam("endTime", qEndTime); err != nil {
			return err
		}
	}

	if o.OrganizationID != nil {

		// query param organizationId
		var qrOrganizationID string

		if o.OrganizationID != nil {
			qrOrganizationID = *o.OrganizationID
		}
		qOrganizationID := qrOrganizationID
		if qOrganizationID != "" {

			if err := r.SetQueryParam("organizationId", qOrganizationID); err != nil {
				return err
			}
		}
	}

	// query param startTime
	qrStartTime := o.StartTime
	qStartTime := qrStartTime.String()
	if qStartTime != "" {

		if err := r.SetQueryParam("startTime", qStartTime); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
